# ==============================================================================
# OdysseyWM Window Appearance
# Navigate Beyond
# ==============================================================================

# Wallpaper
output * bg /home/magikxiii/Pictures/Wallpapers/Osaka.jpg  fill

# Remove old i3-style title bars
default_border pixel 2
default_floating_border pixel 2

# Cleaner tiling behavior
smart_borders on

