# ==============================================================================
# OdysseyWM Environment
# Navigate Beyond
# ==============================================================================

# Applications

set $terminal foot
set $launcher wofi
set $browser brave-origin
set $filemanager thunar
set $lock swaylock
